# Generated by Django 4.2.7 on 2026-01-05 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_recoverystabilityanalysis_habitsensitivityanalysis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdata',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
