# Generated by Django 4.2.7 on 2026-01-05 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommendation', '0003_alter_healthdata_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('food', 'Food/Meal'), ('water', 'Water'), ('exercise', 'Exercise'), ('medication', 'Medication'), ('sleep', 'Sleep')], max_length=20)),
                ('time', models.TimeField(help_text='Time for reminder')),
                ('message', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('days_of_week', models.JSONField(default=list, help_text='Days of week (0=Monday, 6=Sunday)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='HealthRiskAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], max_length=20)),
                ('alert_type', models.CharField(choices=[('weight', 'Weight Issue'), ('bmi', 'BMI Risk'), ('sleep', 'Sleep Deprivation'), ('exercise', 'Lack of Exercise'), ('diet', 'Poor Diet'), ('disease', 'Disease Risk')], max_length=50)),
                ('message', models.TextField()),
                ('recommendations', models.JSONField(default=list)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiseasePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_type', models.CharField(max_length=100)),
                ('risk_score', models.FloatField(help_text='Risk score (0-100)')),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], max_length=20)),
                ('factors', models.JSONField(default=list, help_text='Contributing factors')),
                ('recommendations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
    ]
