# Generated by Django 4.2.7 on 2026-01-05 17:42

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommendation', '0004_reminder_healthriskalert_diseaseprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthdata',
            name='total_calories',
            field=models.FloatField(default=0, help_text='Total calories from food entries'),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='total_carbs',
            field=models.FloatField(default=0, help_text='Total carbs in grams'),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='total_fats',
            field=models.FloatField(default=0, help_text='Total fats in grams'),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='total_fiber',
            field=models.FloatField(default=0, help_text='Total fiber in grams'),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='total_protein',
            field=models.FloatField(default=0, help_text='Total protein in grams'),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='water_intake_liters',
            field=models.FloatField(blank=True, help_text='Water intake in liters', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.CreateModel(
            name='FoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snacks', 'Snacks')], max_length=20)),
                ('food_name', models.CharField(max_length=200)),
                ('quantity', models.FloatField(default=1.0, help_text='Quantity (servings or grams)')),
                ('unit', models.CharField(default='serving', help_text='Unit: serving, gram, cup, etc.', max_length=20)),
                ('calories_per_unit', models.FloatField(default=0)),
                ('protein_per_unit', models.FloatField(default=0)),
                ('carbs_per_unit', models.FloatField(default=0)),
                ('fats_per_unit', models.FloatField(default=0)),
                ('fiber_per_unit', models.FloatField(default=0)),
                ('total_calories', models.FloatField(default=0)),
                ('total_protein', models.FloatField(default=0)),
                ('total_carbs', models.FloatField(default=0)),
                ('total_fats', models.FloatField(default=0)),
                ('total_fiber', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('health_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_entries', to='recommendation.healthdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'meal_type'],
            },
        ),
    ]
